name: xmshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.8.4
  card_swiper: ^2.0.4
  dio: ^5.2.1+1
  flutter_staggered_grid_view: ^0.6.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: aliFonts
      fonts:
        - asset: assets/fonts/iconfont.ttf

